# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

Libraries

In [157]:
import pandas as pd
import numpy as np 
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [158]:
# Definining the paths 
df_1 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')
df_2 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv')
df_3 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv')

In [159]:
# df_1
# df_2
# df_2

In [160]:
df_1 = df_1.rename(columns={'ST':'State', 'GENDER':'Gender'})
df_2 = df_2.rename(columns={'ST':'State', 'GENDER':'Gender'})
df_3 = df_3.rename(columns={'ST':'State', 'GENDER':'Gender'})

In [161]:
# combined = df_1.merge(df_2, on='Customer', how ='outer')
# #df = combined.merge(df_3, on='Customer', how='outer')
# combined

In [162]:
df = pd.concat([df_1, df_2, df_3], ignore_index=True) # too much duplicates, merging was a better option
df

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [163]:
df['Customer'].nunique()

9056

In [164]:
df[df.duplicated(subset='Customer', keep=False)].sort_values(by='Customer', ascending=True)

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
5825,AC40767,Washington,M,Bachelor,2497.808174,68041.0,64.0,0,Personal Auto,Two-Door Car,165.570243
741,AC40767,Washington,M,Bachelors,249780.82%,68041.0,6464.0,1/0/00,Personal Auto,Two-Door Car,165.570243
4643,AI49712,Washington,F,High School or Below,259389.79%,0.0,72.0,1/0/00,Personal Auto,Four-Door Car,345.600000
6529,AI49712,Washington,F,High School or Below,2593.897887,0.0,72.0,0,Personal Auto,Four-Door Car,345.600000
416,AX86150,Washington,M,High School or Below,265671.31%,62777.0,67.0,1/0/00,Personal Auto,Two-Door Car,101.288069
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
df.sort_values(by='Customer', ascending=True)

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
6848,AA10041,California,M,High School or Below,7901.744238,0.0,113.0,0,Personal Auto,SUV,1258.327804
5804,AA11235,Nevada,F,Bachelor,2568.843396,11167.0,73.0,3,Personal Auto,Two-Door Car,350.400000
5054,AA16582,Washington,M,Bachelor,24127.50402,14072.0,71.0,0,Personal Auto,Four-Door Car,511.200000
11134,AA30683,California,M,Bachelor,6595.101921,0.0,105.0,2,Personal Auto,Four-Door Car,847.717402
7383,AA34092,California,M,College,28799.95415,33635.0,240.0,0,Personal Auto,Luxury SUV,1152.000000
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
df.sort_values(by=df.columns.tolist(), na_position='last') # Sort by number of missing values (fewer NaNs = better rows)

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
6848,AA10041,California,M,High School or Below,7901.744238,0.0,113.0,0,Personal Auto,SUV,1258.327804
5804,AA11235,Nevada,F,Bachelor,2568.843396,11167.0,73.0,3,Personal Auto,Two-Door Car,350.400000
5054,AA16582,Washington,M,Bachelor,24127.50402,14072.0,71.0,0,Personal Auto,Four-Door Car,511.200000
11134,AA30683,California,M,Bachelor,6595.101921,0.0,105.0,2,Personal Auto,Four-Door Car,847.717402
7383,AA34092,California,M,College,28799.95415,33635.0,240.0,0,Personal Auto,Luxury SUV,1152.000000
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
df = df.drop_duplicates(subset='Customer', keep='first')
df

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [168]:
df.columns

Index(['Customer', 'State', 'Gender', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [169]:
df_customer = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')
# df_customer

In [170]:
df_customer.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [171]:
# Getting rid of the underscores in the column names and replacing them with spaces and captilizing the first letter of each word
df_customer.columns = [col.replace('_', ' ').title() for col in df_customer.columns]
df_customer

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,Employmentstatus,Gender,...,Number Of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type,Month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [172]:
pivot_table = pd.pivot_table(
    df_customer,
    index='Sales Channel', 
    values = 'Total Claim Amount',
    aggfunc='sum')

pivot_table = pivot_table.round(2)
print(pivot_table)

               Total Claim Amount
Sales Channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

In [173]:
type(df_customer)

pandas.core.frame.DataFrame

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [174]:
pivot_table = pd.pivot_table(
    df_customer, 
    index='Gender', 
    columns='Education', 
    values = 'Customer Lifetime Value', 
    aggfunc='mean'
).round(2)
print(pivot_table)

Education  Bachelor  College   Doctor  High School or Below   Master
Gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

In [175]:
# Converting the date column to datetime
df_customer['Effective To Date'] = pd.to_datetime(df_customer['Effective To Date'])

# Extracting the month name
df_customer['Month'] = df_customer['Effective To Date'].dt.month_name()

# Filter rows where there is at least one complaint
complaints_df = df_customer[df_customer['Number Of Open Complaints'] > 0]

# Group by Policy Type and Month, and count complaints
summary = complaints_df.groupby(['Policy Type', 'Month']).size().reset_index(name='Number of Complaints')

# Sort by number of complaints if needed
summary = summary.sort_values(by='Number of Complaints', ascending=False)
print(summary)

      Policy Type     Month  Number of Complaints
3   Personal Auto   January                  1102
2   Personal Auto  February                   965
1  Corporate Auto   January                   314
0  Corporate Auto  February                   268
5    Special Auto   January                    51
4    Special Auto  February                    50